plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'ru.altrimo.slad2025'
    compileSdk 35

    defaultConfig {
        applicationId "ru.altrimo.slad2025"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }


    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        debug {
            debuggable true
            buildConfigField 'String', 'API_URL', '"http://45.10.111.32:8080/fevral_test/hs/tsd/"'
            buildConfigField 'String', 'API_USER', '"ws"'
            buildConfigField 'String', 'API_PASSWORD', '"123"'
            buildConfigField 'String', 'PREFERENCES_NAME ', '"AltrimoPreferences "'
        }
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.swiperefreshlayout
    implementation libs.play.services.mlkit.barcode.scanning
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core


    def nav_version = "2.5.2"
    // Views/Fragments Integration
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Feature module support for Fragments
    implementation "androidx.navigation:navigation-dynamic-features-fragment:$nav_version"

    //hilt
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-compiler:2.51.1"

    //Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'

    //okhttp
    def okHttpVersion = "4.9.1"
    api "com.squareup.okhttp3:okhttp:$okHttpVersion"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:$okHttpVersion"
    api "com.squareup.okhttp3:logging-interceptor:$okHttpVersion"

    //reflect
    implementation "org.jetbrains.kotlin:kotlin-reflect:1.8.22"

    //API сканирования штрих-кода
    implementation 'com.google.mlkit:barcode-scanning:17.2.0'
    // Библиотека CameraX
    def camerax_version = "1.3.4"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
    implementation "androidx.camera:camera-view:1.4.0-beta02"

    implementation 'com.google.guava:guava:27.1-android'
}

kapt {
    correctErrorTypes true
}